### ISSUE TITLE
Hydro Raindrop

### ISSUE THREAD

**Issue by Raozeeshan73** [hydrogen-dev/hcdp#88]
https://steemit.com/hydrogen/@raozeeshan73/2iu2c2-hydro-raindrop
0xF59217418f02c5BBEe52734e6B1FE46879d1e8AA

**Comment by myyigit** [comment]
https://steemit.com/hydrogen/@myyigit/hydrogen-yagmur-damlasi-raindrop

0x4aCb01c2139A247C10f249FA5B5837C75D5565B3

**Comment by Raozeeshan73** [comment]
Hello, I changed the authentication and update the comment. Kindly check it
sorry for authentication.

**Comment by NoahHydro** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
