### ISSUE TITLE
Security of Hydro

### ISSUE THREAD

**Issue by Raozeeshan73** [hydrogen-dev/hcdp#96]
https://steemit.com/hydrogen/@raozeeshan73/security-of-hydro

0xF59217418f02c5BBEe52734e6B1FE46879d1e8AA

**Comment by NoahHydro** [comment]
Thank you for your submission! We appreciate your involvement with the Hydro ecosystem.

Unfortunately, this post doesn't meet the standards of the HCDP; it does not provide an original, detailed, informative view of Hydrogen products. We’re currently looking for posts that add an additional layer of uniqueness beyond summarizing our current white paper or existing product offerings.
